rocsmt:
  src_file_path: rocsmt/test/raw.en.test
  ref_file_path: rocsmt/test/ref.fr.test
  src_lang: English
  tgt_lang: French
  ugc_annotations_file_path: rocsmt/rocsmt_ugc_annotations.txt

footweets:
  src_file_path: footweets/detok.twitter.sent.en.txt
  ref_file_path: footweets/detok.twitter.sent.de.txt
  src_lang: English
  tgt_lang: German

mmtc:
  src_file_path: mmtc/test.fr-en.fr
  ref_file_path: mmtc/test.fr-en.en
  src_lang: French
  tgt_lang: English

pfsmb:
  src_file_path: pfsmb/test.fr
  ref_file_path: pfsmb/test.en
  src_lang: French
  tgt_lang: English
  ugc_annotations_file_path: pfsmb/pfsmb_ugc_annotations.test.txt

pfsmb-dev:
  src_file_path: pfsmb/dev.fr
  ref_file_path: pfsmb/dev.en
  src_lang: French
  tgt_lang: English
  ugc_annotations_file_path: pfsmb/pfsmb_ugc_annotations.dev.txt

pmumt:
  src_file_path: pfsmb/pmumt/crapbank_annotated.fr
  ref_file_path: pfsmb/pmumt/crapbank_annotated.en
  src_lang: French
  tgt_lang: English

pmumt-annotations:
  src_file_path: pfsmb/pmumt/annotations.fr
  ref_file_path: pfsmb/pmumt/annotations.en
  src_lang: French
  tgt_lang: English

rocsmt-gpt:
  src_file_path: rocsmt/test/raw.en.test
  ref_file_path: rocsmt/test/gpt.ref.fr.test
  src_lang: English
  tgt_lang: French

footweets-gpt:
  src_file_path: footweets/detok.twitter.sent.en.txt
  ref_file_path: footweets/gpt.detok.twitter.sent.de.txt
  src_lang: English
  tgt_lang: German

mmtc-gpt:
  src_file_path: mmtc/test.fr-en.fr
  ref_file_path: mmtc/gpt.test.fr-en.en
  src_lang: French
  tgt_lang: English

pfsmb-gpt:
  src_file_path: pfsmb/test.fr
  ref_file_path: pfsmb/gpt.test.en
  src_lang: French
  tgt_lang: English